name: uveye_env_bkp3
channels:
  - bioconda
  - hangyu1234
  - Meepio
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.4.0
  - blas=1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpython=3.10.19
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.6
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - intel-openmp=2022.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpciaccess=0.18
  - libpng=1.6.50
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libva=2.22.0
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.8.1
  - networkx=3.4.2
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.3.0
  - openssl=3.6.0
  - pillow=9.4.0
  - pip=25.3
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.2
  - svt-av1=1.2.0
  - sympy=1.14.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - typing_extensions=4.15.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - arrow==1.4.0
      - astroid==3.3.11
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - asyncssh==2.21.1
      - atomicwrites==1.4.1
      - attrs==25.4.0
      - autopep8==2.0.4
      - babel==2.17.0
      - backports-tarfile==1.2.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - binaryornot==0.4.4
      - black==25.11.0
      - bleach==6.3.0
      - cattrs==25.3.0
      - chardet==5.2.0
      - click==8.3.0
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cookiecutter==2.6.0
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diff-match-patch==20241021
      - dill==0.4.0
      - docstring-to-markdown==0.17
      - docutils==0.21.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - flake8==7.1.2
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - inflection==0.5.1
      - intervaltree==3.1.0
      - ipykernel==6.31.0
      - ipython==8.37.0
      - ipython-pygments-lexers==1.1.1
      - isort==6.1.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jedi==0.19.2
      - jeepney==0.9.0
      - jellyfish==1.2.1
      - jmespath==0.10.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - keyring==25.6.0
      - kiwisolver==1.4.9
      - lsprotocol==2025.0.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mmcv==2.2.0
      - mmdet==3.2.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - more-itertools==10.8.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpydoc==1.9.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pycodestyle==2.12.1
      - pycryptodome==3.23.0
      - pydocstyle==6.3.0
      - pyflakes==3.2.0
      - pygithub==2.8.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylint==3.3.9
      - pylint-venv==3.0.4
      - pyls-spyder==0.4.0
      - pynacl==1.6.1
      - pyparsing==3.2.5
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.17.1
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.18
      - python-dateutil==2.9.0.post0
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-ruff==2.3.0
      - python-lsp-server==1.13.1
      - python-slugify==8.0.4
      - pytokens==0.3.0
      - pytoolconfig==1.3.1
      - pytz==2023.4
      - pyuca==1.2
      - pyxdg==0.28
      - pyzmq==27.1.0
      - qdarkstyle==3.2.3
      - qstylizer==0.2.4
      - qtawesome==1.4.0
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - referencing==0.37.0
      - requests==2.28.2
      - rich==13.4.2
      - rope==1.14.0
      - rpds-py==0.28.0
      - rtree==1.4.1
      - ruff==0.14.4
      - scipy==1.15.3
      - secretstorage==3.4.1
      - setuptools==60.2.0
      - shapely==2.1.2
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - spyder==6.1.0
      - spyder-kernels==3.1.1
      - stack-data==0.6.3
      - superqt==0.7.6
      - tabulate==0.9.0
      - termcolor==3.2.0
      - terminaltables==3.1.10
      - text-unidecode==1.3
      - textdistance==4.6.3
      - three-merge==0.1.1
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tornado==6.5.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - triton==3.0.0
      - tzdata==2025.2
      - ujson==5.11.0
      - ultralytics==8.3.228
      - ultralytics-thop==2.0.18
      - urllib3==1.26.20
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - whatthepatch==1.0.7
      - wurlitzer==3.1.1
      - yapf==0.43.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/kerencohen2/.conda/envs/uveye_env_bkp3
