name: uveye_env
channels:
  - bioconda
  - hangyu1234
  - Meepio
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - arrow==1.4.0
      - astroid==3.2.4
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - asyncssh==2.21.1
      - atomicwrites==1.4.1
      - attrs==25.3.0
      - autopep8==2.0.4
      - babel==2.17.0
      - backcall==0.2.0
      - backports-tarfile==1.2.0
      - backports-zoneinfo==0.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - binaryornot==0.4.4
      - black==24.8.0
      - bleach==6.1.0
      - cachetools==5.5.2
      - certifi==2025.11.12
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.1.1
      - cookiecutter==2.6.0
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diff-match-patch==20241021
      - dill==0.4.0
      - docstring-to-markdown==0.17
      - docutils==0.20.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - flake8==7.1.2
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - future==1.0.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - idna==3.11
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - inflection==0.5.1
      - intervaltree==3.1.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - isort==5.13.2
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jedi==0.19.2
      - jeepney==0.9.0
      - jellyfish==1.1.3
      - jinja2==3.1.6
      - jmespath==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - keyring==25.5.0
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mmcv==2.1.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.1.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.0
      - numpy==1.24.1
      - numpydoc==1.7.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - protobuf==5.29.5
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydocstyle==6.3.0
      - pyflakes==3.2.0
      - pygithub==2.8.1
      - pygments==2.19.2
      - pyjwt==2.9.0
      - pylint==3.2.7
      - pylint-venv==3.0.4
      - pyls-spyder==0.4.0
      - pynacl==1.6.1
      - pyparsing==3.1.4
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.15.0
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.18
      - python-dateutil==2.9.0.post0
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-server==1.12.2
      - python-slugify==8.0.4
      - pytoolconfig==1.3.1
      - pytz==2023.4
      - pyuca==1.2
      - pyxdg==0.28
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qdarkstyle==3.2.3
      - qstylizer==0.2.4
      - qtawesome==1.4.0
      - qtconsole==5.6.1
      - qtpy==2.4.3
      - referencing==0.35.1
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - rope==1.14.0
      - rpds-py==0.20.1
      - rsa==4.9.1
      - rtree==1.3.0
      - scipy==1.10.1
      - secretstorage==3.3.3
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sphinx==7.1.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - spyder==6.0.8
      - spyder-kernels==3.0.5
      - stack-data==0.6.3
      - superqt==0.6.7
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - text-unidecode==1.3
      - textdistance==4.6.3
      - three-merge==0.1.1
      - tinycss2==1.2.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tornado==6.4.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - ujson==5.10.0
      - urllib3==1.26.20
      - watchdog==4.0.2
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - werkzeug==3.0.6
      - whatthepatch==1.0.6
      - wurlitzer==3.1.1
      - yapf==0.43.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/kerencohen2/.conda/envs/uveye_env
